#!/usr/bin/env python3.6
from user import User
from credentials import  Credential
import random

def create_user_account(user_name,passcode):
    new_user = User(user_name,passcode)
    return new_user

def save_user(user):
    user.saveUser()

def check_user(user_name,passcode):
    user_found = User.user_exists(user_name,passcode)
    return user_found




"""credentials"""

def create_credential_account(acc,pasw,usr):
    new_credential = Credential(acc,pasw,usr)
    return new_credential

def save_credential(credential):
    credential.save_credentials()

def create_password():
    password = ''
    vowel = ['a','e','i','o','u']
    conso = "BCDFGHJKLMNOO"
    for x in range(6):
        password += random.choice(conso) + random.choice(vowel)

    return password

def display_credentials():
    return Credential.displayCredentials()

def delete_credentials(credential):
    credential.delete_credential()

def search_credential(name):
    return Credential.search_account(name)


def credential_exists(name):
    return Credential.credential_exist


















"""
Main function
"""

def main():
    print('Hello Welcome to the PASSWORD LOCKER APP')
    while True:
            
       
        print('Use the short codes:\n')
        print()
        print('L -> To log into your existing PASSWORD LOCKER account')
        print('C -> To create a new PASSWORD LOCKER account\n')
        print('x -> To exit app\n')

        print('#'*80)
        
        short_code = input().lower().strip()
        if short_code =='c':
            username = input('What username should be assigned to your password locker accunt?\n')
            password = input('Enter password\n')
            print('Creating Your passwordlocker account.......')
            new_user = create_user_account(username,password)

            save_user(new_user)
            print('Account created\n')

        elif short_code == 'l':

            username = input('Enter your username\n')
            password = input('Enter your password\n')
            print('\n')
            user_exists = check_user(username,password)
            if user_exists:
        
                print(f'Welcome {username} . Login was successful')
                while True:
                    print('Use the following short codes')
                    print()
                    print('cc -> To create a new credentials account')
                    print('dc -> To display all credentials\n')
                    print('dd -> To delete a credential\n')
                    print('#'*80)

                    credential_codes = input().lower().strip()

                    if credential_codes == "cc":

                        cred_account = input('For which app are these credentials for?\n')
                        cred_username = input('Enter your username\n')
                        
                        print('Do you prefer an autogenerated password ? type Y to agree and N to disagree')
                        
                        while True:
                            response  = input().lower().strip()
                            if response == 'y':
                                cred_password = create_password()
                                break
                            elif response == 'n':
                                cred_password = input('Enter your own password\n')
                                break
                            else:
                                print('Invalid response type Y to agree and N to disagree')
                                continue
                        save_credential(create_credential_account(cred_account,cred_password,cred_username))
                        print(f'-----------------------credential for {cred_account} has been added----------------------------')
                         
                    elif credential_codes == "dc":

                        if display_credentials():
                             print('Here is a list of all your credential accounts\n')
                             
                             for credential in display_credentials():
                                 print(f'Account:{credential.account}' , end = '---')
                                 print(f'Username:{credential.username}' , end = '--- ')
                                 print(f'Password:{credential.password}')
                                 print('\n')
                        else:
                             print('----------You dont seem tohave any credentials at this time')


                    elif credential_codes == "dd":
                        if display_credentials():
                            print('Enter the credential account to delete')
                            account_name = input().lower
                            if credential_exists(account_name):
                                found_credential = search_credential(account_name)
                                found_credential.delete_credential()
                                print(f'Successfully deleted your {account_name} credential accountn')
                                
                            else:
                                print('Credential account does not even exist')

                        else:
                            print('---------------------Sorry You have no credential account---------------------\n')


            else:
                print('-----------User not found or Incorect login details--------------------\n')




        elif short_code == 'x':
            print('------BYE-------\n')


        else:
            print("I really didn't get that. Please use the short codes\n")







if __name__ == '__main__':

    main()
